#!/bin/zsh
set -e

zparseopts \
	-use-workflow:=workflow_id \
	-runner:=runner

config_file=$(realpath $0)
config_file=$(dirname $config_file)/config.yaml

export TOKEN=$(yq '.token' $config_file | jq -r '.')
export http_proxy=$(yq '.http_proxy' $config_file | jq -r '.')
export https_proxy=$(yq '.https_proxy' $config_file | jq -r '.')
repo=$(yq ".runner.\"$(basename $0)\"" $config_file | jq -r '.')
artifacts_repo=$(yq ".repo.artifacts" $config_file | jq -r '.')
eval artifacts_repo=$artifacts_repo

[ "$http_proxy" = "null" ] && unset http_proxy
[ "$https_proxy" = "null" ] && unset https_proxy
[ -n "$runner" ] && repo=${runner[2]}
[ "$repo" = "null" ] && echo "No runner specific." >>/dev/stderr && exit 1
workflow_id=${workflow_id[2]}

package=$(realpath .)
package=$(basename $package)
uuid=$(uuidgen)

if [ -z "$workflow_id" ]
then
	curl -sS -X POST https://api.github.com/repos/${repo}/dispatches \
		-H "Accept: application/vnd.github.everest-preview+json" \
		-H "Authorization: token $TOKEN" \
		--data "{\"event_type\": \"$package $uuid\"}"

	while true
	do
		sleep 30
		workflow_id=$(download-file-from-artifact.zsh \
			--repo ${repo} \
			--file $package.$uuid \
			--type file) || continue
		break
	done
fi

download-file-from-artifact.zsh \
	--repo ${repo} \
	--workflow $workflow_id \
	--file $package.log \
	--type file \
	--save-json /tmp/$package.$uuid.artifacts.json > /tmp/$package.$uuid.log || exit 1

cat /tmp/$package.$uuid.log >> /dev/stderr
rm /tmp/$package.$uuid.log

download-file-from-artifact.zsh \
	--repo ${repo} \
	--workflow $workflow_id \
	--file $package.patch \
	--type file > /tmp/$package.$uuid.patch ||
	rm -f /tmp/$package.$uuid.patch

if [ -f /tmp/$package.$uuid.patch ]
then
	for i in $(git status -s | grep " M" | cut -c 4-)
	do
		git checkout -- $i
	done

	for i in $(git status -s | grep "^A" | cut -c 4-)
	do
		rm $i
	done

	git am /tmp/$package.$uuid.patch
	rm /tmp/$package.$uuid.patch
fi

download-file-from-artifact.zsh \
	--repo ${repo} \
	--workflow $workflow_id \
	--file $package \
	--type package \
	--save-path . || exit 1

if [ -n "$artifacts_repo" ]
then
	cd "$artifacts_repo"
	git pull origin master
	cp /tmp/$package.$uuid.artifacts.json $package.json
	git add $package.json
	git commit -m "[${repo}] uploaded artifacts for $package" -m "https://github.com/$repo/actions/runs/$workflow_id"
	while true
	do
		git push origin master && break || git pull --rebase origin master
		sleep $(($RANDOM%10/10.0))
	done
fi

rm -f /tmp/$package.$uuid*
