name: build

on:
  repository_dispatch:

jobs:

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
        with:
          path: action-tools

      - uses: actions/checkout@master
        with:
          repository: petronny/lilac
          path: lilac

      - uses: actions/checkout@master
        with:
          repository: arch4edu/action-artifacts
          path: artifacts

      - name: Initialize
        id: initialization
        run: ${GITHUB_WORKSPACE}/action-tools/initialize.sh

      - uses: actions/checkout@master
        with:
          repository: arch4edu/arch4edu
          path: arch4edu

      - uses: actions/checkout@master
        with:
          repository: arch4edu/mirrorlist
          path: mirrorlist

      - run: configure-arch4edu.sh

      - run: pre-build.sh

      - name: Build the package with lilac
        env:
          TOKEN: ${{ secrets.CALIL_GITHUB_TOKEN }}
          PYTHONPATH: ${{ github.workspace }}/lilac:${{ github.workspace }}/lilac/vendor:${{ github.workspace }}/action-tools
        run: |
          cd ${GITHUB_WORKSPACE}/arch4edu/${{ steps.initialization.outputs.pkgbase }}
          ls -al
          set -o pipefail
          python lilac.py action | tee ${GITHUB_WORKSPACE}/build.log
          [ ${PIPESTATUS[0]} -eq 0 ] && git format-patch HEAD~1 . --stdout > ~/commit.patch || rm -f ~/commit.patch

      - run: post-build.sh

      - name: Upload workflow id
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.initialization.outputs.pkgbase }}.${{ steps.initialization.outputs.uuid }}
          path: ${{ github.workspace }}/workflow_id

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.initialization.outputs.pkgbase }}
          path: ${{ github.workspace }}/arch4edu/${{ steps.initialization.outputs.pkgbase }}/*.pkg.tar.zst

      - name: Upload commit patch
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.initialization.outputs.pkgbase }}.patch
          path: ${{ github.workspace }}/commit.patch

      - name: Upload build log
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: ${{ steps.initialization.outputs.pkgbase }}.log
          path: ${{ github.workspace }}/build.log
